spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PersonTab
    username: root
    password: root

    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate:
        format_sql: true