GET http://localhost:8080/person/

###

POST http://localhost:8080/person/ HTTP/1.1
content-type: application/json

{ 
    "id" : 1, 
    "name" : "sujit", 
    "age" : 23
}

###

PUT http://localhost:8080/person/1 HTTP/1.1 
content-type: application/json

{ 
    "name" : "Sanket", 
    "age" : 24
}
###

DELETE http://localhost:8080/person/1